---
title: "Conclusion"
author: "Mariana Llamas-Cendon"
date: "10/16/2016"
output: 
  html_document:
    keep md: yes
---

```{r echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)

setwd("/Users/marianallamas-cendon/Desktop/git_repositories/DSPostLiveAssignment6/QueensHousing/Data")

bk <- read.csv("rollingsales_queens.csv",skip=4,header=TRUE)


bk$SALE.PRICE.N <- as.numeric(gsub("[^[:digit:]]","", bk$SALE.PRICE))
names(bk) <- tolower(names(bk)) 
bk$gross.sqft <- as.numeric(gsub("[^[:digit:]]","", bk$gross.square.feet))
bk$land.sqft <- as.numeric(gsub("[^[:digit:]]","", bk$land.square.feet))
bk$year.built <- as.numeric(as.character(bk$year.built))
attach(bk)
hist(sale.price.n) 
detach(bk)
bk.sale <- bk[bk$sale.price.n!=0,]
```

```{r}
knitr::opts_chunk$set(echo = FALSE)
plot(bk.sale$gross.sqft,bk.sale$sale.price.n)
```

```{r}
knitr::opts_chunk$set(echo = FALSE)
plot(log10(bk.sale$gross.sqft),log10(bk.sale$sale.price.n))
```

```{r}
knitr::opts_chunk$set(echo = FALSE)

bk.homes <- bk.sale[which(grepl("FAMILY",bk.sale$building.class.category)),]
```

```{r}
knitr::opts_chunk$set(echo = FALSE)

plot(log10(bk.homes$gross.sqft),log10(bk.homes$sale.price.n))
```

```{r  results='hide'}
knitr::opts_chunk$set(echo = FALSE)

summary(bk.homes[which(bk.homes$sale.price.n<100000),])
bk.homes$outliers <- (log10(bk.homes$sale.price.n) <=5) + 0
bk.homes <- bk.homes[which(bk.homes$outliers==0),]
```

```{r}
knitr::opts_chunk$set(echo = FALSE)
plot(log(bk.homes$gross.sqft),log(bk.homes$sale.price.n))
```



